name: Mac 64
on: [push]
jobs:
  test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          version: 110.0.5481.30
          arch: mac64
          download-path: temp
